Verify release tag exists

diff --git a/.github/workflows/publish-release.yml b/.github/workflows/publish-release.yml
--- a/.github/workflows/publish-release.yml
+++ b/.github/workflows/publish-release.yml
@@ -40,7 +40,14 @@ jobs:
           cache: 'maven'
       - name: Determine Version
         id: version
+        env:
+          REF: ${{ github.event.workflow_run.head_branch }}
         run: |
+          if ! git show-ref --exists "refs/tags/$REF"; then
+            echo "::error ::Tag $REF does not exist, aborting."
+            exit 1
+          fi
+          
           VERSION=$(./mvnw --batch-mode --no-transfer-progress help:evaluate -Dexpression=project.version -q -DforceStdout)
           echo "Determined VERSION=$VERSION"
           if [[ "$VERSION" = *-SNAPSHOT ]]; then
